
CREATE TABLE MEMBER
(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  ACCOUNT VARCHAR(30) NOT NULL COMMENT '',
  CREATE_TIME DATETIME NOT NULL COMMENT '生成时间',
  PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='core库表';

INSERT INTO MEMBER(ID,ACCOUNT,CREATE_TIME) VALUE(1,'admin',SYSDATE());

CREATE TABLE JOB_TASK
(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  JOB_NAME VARCHAR(30) NOT NULL COMMENT '',
  CREATE_TIME DATETIME NOT NULL COMMENT '生成时间',
  PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='schedule库表';

INSERT INTO JOB_TASK(ID,JOB_NAME,CREATE_TIME) VALUE(1,'taskName',SYSDATE());


CREATE TABLE MEMBER_ORDER
(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  ORDER_NO VARCHAR(30) NOT NULL COMMENT '',
  CREATE_TIME DATETIME NOT NULL COMMENT '生成时间',
  PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='core/schedule库都存在的表';

INSERT INTO MEMBER_ORDER(ID,ORDER_NO,CREATE_TIME) VALUE(1,'core_100',SYSDATE());
INSERT INTO MEMBER_ORDER(ID,ORDER_NO,CREATE_TIME) VALUE(1,'schedule_200',SYSDATE());