
CREATE TABLE MEMBER
(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  ACCOUNT VARCHAR(30) NOT NULL COMMENT '',
  CREATE_TIME DATETIME NOT NULL COMMENT '生成时间',
  PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='core库表';

INSERT INTO MEMBER(ID,ACCOUNT,CREATE_TIME) VALUE(1,'admin',SYSDATE());

CREATE TABLE JOB_TASK
(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  JOB_NAME VARCHAR(30) NOT NULL COMMENT '',
  CREATE_TIME DATETIME NOT NULL COMMENT '生成时间',
  PRIMARY KEY (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='schedule库表';


INSERT INTO JOB_TASK(ID,JOB_NAME,CREATE_TIME) VALUE(1,'taskName',SYSDATE());